{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "file_server_bytes_received_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "active_connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "file_server_active_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "lab2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  }
 ]
}